name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Git Secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          cd ..
          git secrets --install
          git secrets --register-aws
          git secrets --add 'eyJhbGciOiJIUzI1NiIsInR5cCI'
          git secrets --add '(password|passwd|secret|credential|token|auth|key).*[=:][[:space:]]*[^[:space:]]*'
          git secrets --add 'DATABASE_URL.*=.*'

      - name: Scan for secrets
        run: git secrets --scan-history

      - name: TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog-actions-scan@master
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
